#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: indy-sdk
  description: indy-sdk
  homepage: https://wiki.hyperledger.org/display/indy
  default_branch: main 
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
